### ISSUE TITLE
-psm tesseract parameter is deprecated

### ISSUE THREAD

**Issue by geniass** [openpaperwork/pyocr#101]
Tesseract has deprecated the -psm command line argument (see tesseract-ocr/tesseract@92d981b).

Also in a recent version of Tesseract 4 they have completely removed it (tesseract-ocr/tesseract@ee201e1f4fa277a4b2ecd751a45d3bf1eba6dfdb). This breaks the `WordBoxBuilder`

**Comment by jflesch** [comment]
Duplicate of #99

(Sorry, the issue #99 was closed because @ddddavidmartin submited a pull request. I accepted it (closing the ticket #99) but I had to revert the changes soon after)

**Comment by geniass** [comment]
Sorry didn't see that issue. Thanks.
