### ISSUE TITLE
No OCR tool found

### ISSUE THREAD

**Issue by Williamvdb** [openpaperwork/pyocr#13]
I have tesseract installed. I have used it many times before, but when I use this script:

```
from PIL import Image
import sys

import pyocr
import pyocr.builders

tools = pyocr.get_available_tools()
if len(tools) == 0:
    print("No OCR tool found")
    sys.exit(1)
tool = tools[0]
print("Will use tool '%s'" % (tool.get_name()))


langs = tool.get_available_languages()
print("Available languages: %s" % ", ".join(langs))
lang = langs[0]
print("Will use lang '%s'" % (lang))


txt = tool.image_to_string(Image.open('test.png'),
                           lang=lang,
                           builder=pyocr.builders.TextBuilder())
word_boxes = tool.image_to_string(Image.open('test.png'),
                                  lang=lang,
                                  builder=pyocr.builders.WordBoxBuilder())
line_and_word_boxes = tool.image_to_string(
        Image.open('test.png'), lang=lang,
        builder=pyocr.builders.LineBoxBuilder())
```

It says there is no OCR tool found. Any fix?

**Comment by deqiu** [comment]
@jflesch I use it on Win10, and I also get ''No OCR Tool Found''. Doesn't it support windows?

**Comment by jflesch** [comment]
It does support Windows (see https://openpaper.work/download ). However, Tesseract.exe must be in your PATH.

**Comment by viswa20** [comment]
hi @jflesch i can't found any exe in your package. Can you help me on this

**Comment by jflesch** [comment]
There are no .exe in Pyocr. Pyocr is a Python module designed to make it easier to use OCR tools from Python.

Pyocr looks for the OCR tools (Tesseract, Cuneiform, etc) installed on your system and just tells you what it has found.

You have to install Tesseract by yourself.

**Comment by viswa20** [comment]
Thanks for your response

**Comment by LiamLi1** [comment]
dd
