### ISSUE TITLE
Orientation detection failed on Tesseract (C-API)

### ISSUE THREAD

**Issue by Lubo** [openpaperwork/pyocr#57]
Hello, when using Tesseract (C-API) with Tesseract 3.05.00, I get PyocrException with this message when trying to use orientation detection:

```
('detect_orientation failed', 'TessBaseAPIDetectOS() failed')
```

Reason: `TessBaseAPIDetectOS()` is considered unsafe and always returns false. It's also deprecated and may be removed soon.

**Comment by jflesch** [comment]
Darn.

Note to myself:
https://github.com/tesseract-ocr/tesseract/issues/424
https://github.com/tesseract-ocr/tesseract/commit/3a47adcbe13e34f7a1c9ba14e716c8c696077710
^ the new recommended function is not available on all the versions 3.x ... I'll have to handle both APIs ...

**Comment by jflesch** [comment]
Fixed by https://github.com/openpaperwork/pyocr/pull/62
