### ISSUE TITLE
Adding languages

### ISSUE THREAD

**Issue by singhketan** [openpaperwork/pyocr#63]
I'm new to pyocr and ocr in general. I'm trying to use pyocr for languages such as french, chinese etc, but the get_available_languages returns only 3 options: osd, eng, equ. How can I add other languages?

**Comment by jflesch** [comment]
On Debian or Ubuntu: ```apt install tesseract-ocr-fra tesseract-ocr-chi-sim ```

**Comment by jflesch** [comment]
Basically, you (usually) install language data files for Tesseract in the same way you installed Tesseract.
