### ISSUE TITLE
Could we get a confidence value by each word?

### ISSUE THREAD

**Issue by gbc8181** [openpaperwork/pyocr#74]
Hi everyone,

I just noticed that we can get a confidence value of each word by Tesseract API. So I want to know if pyocr can also give us a confidence value of each word? If so, how to do that?

Thanks so much!

**Comment by jflesch** [comment]
Are we talking about the command line tool ```tesseract``` or the library ```libtesseract``` ?

**Comment by gbc8181** [comment]
I mean tesseract API. APIxample (https://github.com/tesseract-ocr/tesseract/wiki/APIExample) shows they have this function.

**Comment by jflesch** [comment]
Right now it can't.
```pyocr.libtesseract``` could be updated to add the support for that I guess.

**Comment by jflesch** [comment]
Implemented by @a-pagano : https://github.com/openpaperwork/pyocr/pull/86 :-)
