### ISSUE TITLE
I want use chinese char, but acc is low

### ISSUE THREAD

**Issue by dotsonliu** [openpaperwork/pyocr#77]
I want use chinese char,but acc is low,how can i prove it?

**Comment by jflesch** [comment]
I'm sorry but, what is acc ?

**Comment by SingSky** [comment]
Maybe the word "acc" refers to "accuracy"

**Comment by jflesch** [comment]
You're probably right. However, then, it's a question better asked on [Tesseract mailing-list](https://groups.google.com/forum/#!forum/tesseract-ocr) than here. Pyocr is just a Python binding for Tesseract and Cuneiform. I don't know much about the internals of Tesseract.
