### ISSUE TITLE
The result is empty

### ISSUE THREAD

**Issue by wning13** [openpaperwork/pyocr#81]
![3](https://user-images.githubusercontent.com/7438062/32643437-77081712-c616-11e7-9dcb-3a761ccee545.gif)
This picture is recognized successfully, but the following picture failed.
![3](https://user-images.githubusercontent.com/7438062/32643438-7779df8c-c616-11e7-95a1-0a03ef864f95.png)
What's wrong with me?

**Comment by jflesch** [comment]
Pyocr is just a wrapper for Tesseract, so this is a question more appropriate for the [Tesseract's mailing-list](https://groups.google.com/forum/#!forum/tesseract-ocr) than for Pyocr's bug tracker.

Tesseract tends to have problems with colors. I guess you can fix this problem by [switching your image to pure black and white](https://stackoverflow.com/a/9506960)

**Comment by wning13** [comment]
Thanks for help!
